import "./globals.css";
import "./fanta.css";

export const metadata = {
  title: "One Stop Productivity Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children} {/* curly braces are what allow Javascript to inject itself into HTML*/}
      </body>
    </html>
  );
}
